--- #YAML:1.0
name:               Net-IP-LPM
version:            0.01_01
abstract:           Perl implementation of Longest Prefix Match algorithm
author:
    - Tomas Podermanski <tpoder@cis.vutbr.cz>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Socket6:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
